name: PR

on: pull_request

jobs:
  build-lint-test:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'open-wc/form-participation'
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node 19.x
        uses: actions/setup-node@master
        with:
          node-version: 19.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: npx lerna run build

      - name: Lint
        run: yarn lint:ci

      - name: Test
        run: yarn test
